### ISSUE TITLE
Change default db_location directory suggestion

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-storage-server#164]
Talking to a SNoper about how they're system is configured using multiple users to isolated each snode on the same server. Notice if we changed the storage servers' default storage directory to be based on their user's home directory, the configuration would be more automatic, more inline with lokid and require the launcher to do a bit less. If we don't change it, then we'll have to have multiple copies of the launcher (or at least a launcher config file for each)

So maybe set a default directory of `~/.loki/storage`

I can make the PR if there's a resource-limitation issue

**Comment by msgmaxim** [comment]
Done in #166
