### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by Fez29** [loki-project/loki-storage-server#216]
My service node stopped sending uptime proofs on testnet due to storage server no longer working it was reporting 

[2019-07-07 05:09:48.164] [error] Error24: Too many open files

To resolve I just stopped loki launcher and restarted it. 

log files of storage-server here:

https://drive.google.com/drive/folders/1SSqvlk1I4Dla85wKv_G1PtMHQ0kckpwt?usp=sharing

**Comment by msgmaxim** [comment]
Thank you for letting us know. We are aware of this problem, and the issue has already been addressed in #211 (currently in dev branch). We will release updated binaries shortly.

**Comment by Fez29** [comment]
Ok thanks, I suspected as much as I built the storage-server manually on my other testnet node from dev branch and it is not suffering the same symptoms but couldnt be sure, I will just build the dev branch of storage server @msgmaxim , closing this issue
