### ISSUE TITLE
Unexpected Prolonged TTL (more than 30 days) for Suspected Config Messages

### ISSUE THREAD

**Issue by venezuela01** [loki-project/loki-storage-server#482]
**Description:**

Recently, users have reported encountering banner messages stating, "Some of your devices are using outdated versions. Syncing may be unreliable until they are updated."

Occasionally, I have observed messages on the storage server with Time-to-Live (TTL) values exceeding 30 days. It is unclear whether this occurrence is coincidental or indicative of a bug, either on the client side or server side, that prevents outdated configuration messages from expiring and causes the banner messages reported by users.

**Steps to Reproduce:**

1. Access a copy of the `storage.db` database.
2. Query the `owned_messages` table/view.
3. Calculate `ttl_day` using the formula `(expiry-timestamp)//(1000*60*60*24)`.
4. Group the results by `ttl_day` and count distinct `owner`, then sort ascending by `ttl_day`.

**Observed Results:**

* The first peak of `owner_count` occurs at `ttl_day==14`, which is consistent with the 14-day TTL for normal messages.
* There is a subsequent peak at `ttl_day==30`, which aligns with the expected 30-day TTL for configuration messages.
* However, numerous owners/messages exhibit TTL values exceeding 30 days, with a maximum of 68 days. This is unexpected.

**Data:**

|  ttl_day  | owner_count |
|:---------:|:-----:|
|     0     |   2   |
|     14    | 1763  |
|     30    | 1906  |
|     31    |  141  |
|     32    |  117  |
|     33    |   87  |
|     34    |   87  |
|     35    |   76  |
|     36    |   67  |
|     37    |   61  |
|     38    |   55  |
|     39    |   56  |
|     40    |   51  |
|     41    |   62  |
|     42    |   53  |
|     43    |   60  |
|     44    |   57  |
|     45    |   50  |
|     46    |   43  |
|     47    |   41  |
|     48    |   40  |
|     49    |   42  |
|     50    |   51  |
|     51    |   68  |
|     52    |   19  |
|     53    |   16  |
|     54    |   15  |
|     55    |   20  |
|     56    |   15  |
|     57    |   20  |
|     58    |   24  |
|     59    |   27  |
|     60    |   21  |
|     61    |   20  |
|     62    |   16  |
|     63    |   22  |
|     64    |   21  |
|     65    |   34  |
|     66    |   28  |
|     67    |   52  |
|     68    |   7   |

**Additional Information:**

- Oxen Storage Server Version: v2.5.0

This report outlines an unexpected behavior where suspected configuration messages appear to have TTL values exceeding the expected 30-day limit. Further investigation and debugging may be required to identify and resolve the issue.

Is there any easy way to validate whether those unexpected messages are config messages, using python / sqlite3?

**Comment by venezuela01** [comment]
@KeeJef

**Comment by venezuela01** [comment]
```
import sqlite3
import pandas as pd

def calculate_ttl_distribution(database_path):
    # Connect to the database
    conn = sqlite3.connect(database_path)

    try:
        # Query the owned_messages table/view and load it into a DataFrame
        query = "SELECT expiry, timestamp, pubkey FROM owned_messages"
        df = pd.read_sql_query(query, conn)

        # Calculate ttl_day
        df['ttl_day'] = (df['expiry'] - df['timestamp']) // (1000 * 60 * 60 * 24)

        # Group by ttl_day and count distinct owners
        result = df.groupby('ttl_day')['pubkey'].nunique().reset_index()

        # Rename the columns for clarity
        result.columns = ['ttl_day', 'owner_count']

        # Sort the result by ttl_day in ascending order
        result = result.sort_values(by='ttl_day')

        return result

    finally:
        # Close the database connection
        conn.close()

# Example usage:
if __name__ == "__main__":
    database_path = "storage.db"
    result_df = calculate_ttl_distribution(database_path)

    print(result_df)
```

**Comment by jagerman** [comment]
> Occasionally, I have observed messages on the storage server with Time-to-Live (TTL) values exceeding 30 days.

This is by design: TTLs of existing messages can be extended indefinitely (with a maximum of +30 days from the time of the extension request).  Session uses this for config messages to keep an existing upload alive rather than needing to periodically re-upload unchanged data.

See https://github.com/oxen-io/oxen-storage-server/blob/0dada891a6f983b2d955f58866132ca2585ade30/oxenss/rpc/client_rpc_endpoints.h#L528-L530 for the API that allows this.

**Comment by jagerman** [comment]
And so what you should *not* see is any messages that expire > 30d from now, not from the original upload timestamp.

**Comment by venezuela01** [comment]
> And so what you should _not_ see is any messages that expire > 30d from now, not from the original upload timestamp.

I see, make sense to me, thanks for explanation!

A related question, when we see Oxen storage server log like:
>      Status: "v2.5.0; sw=<storage server id>(n=7); 273456 msgs (633MB) for 2725 users; reqs(S/R/O/P): 1392/8098/18167/24>
Am I right that it is including more than 30 days of **config** messages now? Is there any plan to add a stats for number of messages/users in the last 30 days?

Edit: `30 days of messages ` -> `30 days of **config** messages `

**Comment by jagerman** [comment]
> Am I right that it is including more than 30 days of config messages now?

I'm not entirely sure what you mean; that is simply a report of all messages that it has currently stored in the database, i.e. it is essentially its current storage usage.

**Comment by venezuela01** [comment]
> I'm not entirely sure what you mean; that is simply a report of all messages that it has currently stored in the database, i.e. it is essentially its current storage usage.

Thanks for the clarification. My initial question wasn't clear, but you've addressed what I was pondering. I had been wondering if the message stats and user stats were based on messages with a `timestamp` spanning more than 30 days. However, I've shifted my focus after reflection. What seems more relevant now is whether the `expiry` of messages is within 30 days from today, which should be true according to https://github.com/oxen-io/oxen-storage-server/issues/482#issuecomment-1710403997. In essence, I'm curious if the storage server stats provide an accurate metric to gauge monthly active users, and it appears they more or less do.
