### ISSUE TITLE
`trace` loglevel not logging trace logs

### ISSUE THREAD

**Issue by martin-braun** [loki-project/loki-storage-server#483]
**Describe the bug**
`--log-level trace` will only log `debug` and no `trace` messages, although the daemon reports "Setting log level to trace". Also giving a wrong log level will just exit the storage server without any printed message, because it tries to log a critical error about the wrong log level before the logger has been initialized. 

So far, I couldn't pin point the root for the main issue (`oxenss` or `oxen-logger`).

**To Reproduce**
- `oxen-storage --log-level trace`
- Neither console nor storage.logs contains "omq:trace"

**Desktop (please complete the following information):**
 - Device: MacBook Pro 2019 16"
 - OS + Version: Debian Bullseye (Parallels VM)
 - Release Version or Github commit hash: https://github.com/oxen-io/oxen-storage-server/commit/0dada891a6f983b2d955f58866132ca2585ade30

**Comment by jagerman** [comment]
Trace logging is only enabled in a debug build, by design: so that we can not be afraid of making trace logging calls in code hot paths (when in a non-debug build, the trace call is a no-op).

**Comment by martin-braun** [comment]
@jagerman Thanks a lot. I wasn't able to pin-point the location where this is happening, but it kinda makes sense. You guessed it right, I was testing with a release build.
