### ISSUE TITLE
Handle key read permission

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-storage-server#90]
**Describe the bug**
If the lokid key does was generated as root and storage server is ran with regular permissions it will silently crash

**To Reproduce**
Generate lokid key as root
Run storage server with regular permissions

**Comment by sachaaaaa** [comment]
Is that what was generating all those logs about the OS not being able to open more files?

**Comment by msgmaxim** [comment]
How many instances of the server are you running? You shouldn't need too many open files (is that about tcp sockets?).
